version: 0.1.0-{build}

skip_tags: false

configuration: Release

clone_folder: C:\wcxhead.rs

install:
  - set PATH=C:\msys64\mingw64\bin;C:\msys64\mingw32\bin;C:\msys64\usr\bin;%PATH%;C:\Users\appveyor\.cargo\bin
  -
  - bash -lc "pacman --needed --noconfirm -Sy pacman-mirrors"
  - bash -lc "pacman --noconfirm -Syyu"
  - bash -lc "pacman --noconfirm -S mingw-w64-x86_64-toolchain bash"
  -
  - curl -SL https://win.rustup.rs/ -oC:\rustup-init.exe
  - C:\rustup-init.exe -y --default-host="x86_64-pc-windows-gnu"

build: off
build_script:
  - git submodule update --init --recursive
  - cargo build --verbose --release
  - cargo doc --verbose --release
  -
  - cp -r target/doc "wcxhead.rs-doc-v0.1.0"
  - tar -caf "wcxhead.rs-doc-v0.1.0.tbz2" "wcxhead.rs-doc-v0.1.0"
  - rm -rf "wcxhead.rs-doc-v0.1.0"

test: off

artifacts:
  - path: wcxhead.rs-doc-v0.1.0.tbz2

deploy:
  provider: GitHub
  artifact: wcxhead.rs-doc-v0.1.0.tbz2
  auth_token:
    secure: q42bVqe6Vo/l9dQyArehIzuhIKUzH2JnsmPExSdliU0JdAn4cJIni87/JIh/QK+Z
  on:
    appveyor_repo_tag: true

notifications:
  - provider: Email
    to: nabijaczleweli@gmail.com
    on_build_status_changed: true
