version: 0.1.0-{build}

skip_tags: false

configuration: Release

clone_folder: C:\wcxhead.rs

environment:
  GH_RSA_ENC:
    secure: zi+WWuI058kvSfZZP8QWTFlh85TVDTrCYvkULpWzktSj4/3g2bHsMV1rucARnNZqUfK7dfmozzieRwkYGJZL0RQzArkrQPEVJFPoIp3i/Ax2cQKFpfiHzT1BEwmI+upuZOuSu4uQ0aCZKmMblfdEm1qG5yAqDxuktNEsGXMcg+SRF6cCM/cFDyOCmZ9KFXqa+5NR8QELJNXnOO1bu2i6jLYcoSw0JEzApksJko5vqtZM6tAtf5Sj/a58a+JjwFixKNGdbs827GC1JoTPtdEMbQboF2nHXch3Gx6KJ9g4iHp+Q/lys3rxIvCCHPkxlVGVPMTe8oQRlwueOwsa/JTicWVYEFNTm5jUqfA0CqB+wa9s8RSftYWjSk5xbDNjQwv4b9KfVCd4LzJJAHUdvYjFPSnbI1km2O8t4G3+HhzelPmpS+F69WIwK8hw7gQq9Uf5+P9oPEDA35NBSXsHjGE2YnkmWzG7E0wabUmVj1Onn0g0roYrNzfH3vsCiJXs+SO19t6TWoPDIcXbfIAdyQDkS6MpUlMM+683lrN01t+24HdJo1kU6aLEt0bcnUZjczwPX72DpdUL9wJInBKoHumw0DFeNNxrGjMZZV4Jso16VZkRXjo+TtLkIUKoMm8fq7OAQ+rc5JcrzjRH7SeYEluCimxHgZNNgDmeaiqoQ4OeXRO1Of4PW6ek2OONTfe/K4XDiNWtv33ad1FSjAuzY3a8SLfipdsuogmKCVpS2+VgoSr0+3IWenbEsIfu9+Le9NnCcVbHXKf33e81tOWAVOohQ5fvvyUJO9LJVOzwpTGyNjdzRi9tcouuagAhXD4b+4E+F9By439I+xYgpPEtjjkcZ+xV5cZe00PPmNPuxh8S7lU/sUmyR1cPk1kAo/VCzBdWZjzrz9oX3PcoMGNa1M7ARasAD458P4FfqwmtJen9HJA+dgJqiwuTiyKe68CMNDthbQbsf+Jc6F2ntdYhwAPrwoo9FmM68X0h+aomb85tfGIBTyDg+O9IJBrfT/sQNbbodw8u3arTdVXse1/CXdjMrd3d/ja/WVQnuDExzSyXQBOQpis5TDsqS80SWgWlspESXeFwxpg7cMhS/EDiB6bdMhWJRfGeVfmr+uc8b8YNNt6CCCesdbi7y6bi4NZrED5WVuX1TXoOHwK6OL30rDU8G7Zz3Rl0aBUv1EUxucCaB28HAaq4R7nL0ze10hKsUupxwRAYtyOdM2YOU507e1M/bjr55l7dFC8uc9IbpBsQgBaapwdJD0VzxeoB4R6tHGktLvM+N3WVIwvVQ+J/N8ZC0MZ1iXDWqk8PMIinBW9WmXJFpKjh9A0n7QvvI3YuzxmPbzKtTzAJir5q/5wV7KbgXG8vceKxH+xw13ad2FhZ037oPHhX7Cy4ELMCjKPYMskhc6KaeDhW5adhonFs2TRo0WK4H4JDF6szI8B0cUzemljMnU5y0Vz9SWfub3d1gwGN/ADtmWZ8ZfWMKtI9LZM+5wCcn+FzfiOWstQtzf1Us1vFrm/yhKXtNRXEa76Z/NEpqi/XFY0/C2/Mr/FPiEYVD8RtS6kfvyamltVy05AuTzc2w5zkv7n9xk0cJ1To6dQ3AyRhEaKifkPmMLVE5v7EnrdibdT7xZu7ImDyuR7hr251LG29cGbQ96i6dBMnK3KA0yFxL6o15b2YOtqR6DbnbVmk7CA68B7HU+tMYOT0CeFGi6qtdyhlabr/VpBvTp2opkmKL01FqjOacjLGh543jn3JqiRuSlWdmGByQeFusPit3uf8pz5sm+LQVowS/oZ5ubp4brVxkGvcdIBLZTxny7/V7A30vy+PcmLI2CnrbSAzFPK03lPqYAy1Rki44hqBd5OBIVotMEItnCeZSic1YzcPzsEBarN10EuanUUfaWcZXkodd2u8wgFodZsDLQxiqzM32gBVVVLC6b7HCqUXEjua8YIo869BS4RfDBSRKSGrnz6D0VHQzkFjmHlEAnek56+YWaDFtBad4mil/WrMjJm9JB2jHFieyBdAHZW8FMiX1cAfEVHRBF40FVnO9JUDaV8UsDGtl6JTCHemC5sv0yGxnv5vw7Q78mGq2z13cdBI/WMVsqgaOwy3wUVTjHu6zbRE+piu0PGpB8gqYCDbMduShs8cRdnewVvSv2KiEWDoMp6NAfhFK9LKmbjvDb64fgD7ztrPXdino814iXPyw4HtxsRXk9zH67z6mS9IQb/qUN6Om2nMNOi4reV+oieQU3tkmPJa55xVYiD/w5fBssGUC4KEESW3OCOgdz1oveRjG8xle00qA9I4HpoxHCeUhdDjusn8z/6HdWYApgevrrOo1hmt3FPqo8e4xZu0GY/LfcmvEkXs/P0kE/zwUteTCaErfLQu7g3X+bclVEaiwCcxl3IaZ8OuUi17UPQqsvZChxLoBbNzA2wpBLNyROctFKCpoIy4EGsk/JYIL+9ezPsZTvBMKVuo7QPHsgR91cwIOUM5JTx0ZOcPFngwi2C98RaXTB+PfZD8E4BPWBH0R/K5nHM7hrm/Nzi8zGEFHiDjXbZW1Hkp164KRUbNFHQSXH2w+jMZfqBxIozXGpTi/Mvb6x6+ICnV5MZjYGLNqqVgqd7YQCfcnKJbz7RZoIA+m/MV98Zwn5HqsZjxwzAES0Q+Jqy+RBD/mSX4+l2VuY55fIBEoJymLXk96wmny/n8hevc0e4l/t3pwl/diGQvWFzBm5BWhw2SH4eVADuyb0iEgu4hx1om9Tk11eW+ifLu8TMaRDVEI2xLnDScimPfark+w8nx9HXVIKWoMCDdKUv6T+8a3PuLH9eCnAAYWsEmbiF8ofFMYD9Rno0jTR5vORksE/jgm3Fjq06Ul2HYhCHAaXBIBNV/iLJuej8wklpiLNLWGF5ahoLaaifDEnR2EmcZiJ2tQp6mhzUZhGoshEqKi5gBAlqLiWj73Uhd17XIxPx4R4r4y5per2RdHjOA04JvK+5NCpqz4qqMLrR7A0GtuQnJ99mTGgsdRbZDvFsqct4HyOnWgeSl1caadkoe1DdBdtuzDT8M8E7fBrxOQPP3g1Fzy1opG4YzF2+HISKsgqAzXKrdgRwdiaDTM1Wl1OlTokP1U5fNPfe5v6WI2xfYd7qWE4xvFc+zdPVHyDmon6D+ZDYJtTQRNdRaHaZwdYMvg2dYAFtvhuH1gmD4ys/hLCzubSkVN0MW4HNimcRJL0cmQjKTJ0Wn5bm//gAIWvIqUQgxAP+eDgjW4n9e3HjFJFxi4cVE4D84mrrA/0N4g+5gmI4J7Mz7QXidgABm/NDBjelpc2zpYb0YdysYbscwXj3g2I7AotxbzQMfKlj1FvxGMuUKiaNnWuGNF05ZDOT+lHCrxV+IUywrndptl22eE6+HwNV3qiATU1K4JAAVI2/+yofL8dLKD0bSTxg+9LBIqWDZgnxQ/ZMx+2aE/SUzdQN3/m6981L7LBh+1HS547K7njzzmNj/Q60/smWeS9VigIEncnELFfyYbU3Of7G1Chd5YDZNkdHYRThVi0bb5gyuEBcLBCesxWiURjY8MdXCJJQ9x16d33CzAL6V3mMb/JHUbJUa6OfoB4kZdOLZKtdm0dEHBAhTADD9JjKYsRsvG/jNo7ihmP5O+N/jhll36UBI+7DHALyndQ0+RaaFWmzopQ7PmSjpXLRb4OQWvTQQ7IvztTkqNKkeRhsIzhGGVOmj7XukaTyQb50x4eIWDMepRjjbZrFVE4+QiaI/4tHvrNfkGK3bxtesfTxbxU4G9qKDjKWjMVjMtF0pfsSll827IsSaL4UmGkumsfacm7CgvRkL5gdZcAzbXXlDl57ais7XfsFwQxj9OewhvYnONsgOsGrhT/zQPPLUUr505Ie/EL75MMxI0NclzsuaMKc1yLbaCons4NeXvt7qKvEe5YijBowcSCNDxSjPGTuJLbkQVX1J8gjrZzgQHgl0U9pxQaoUC/a1O71JyLAs/E7wTNEv3JVP8rXuZQ7TyOJZQQZBjXYcAN7mb9GpFdVMobREeE0GqNEWYm9Ue41xyV5oylthfHlQfMoCkyL2BpSD5Nm/bwKtG4on4wvNNfcrTZqanHywYGOgZ/Bknld2/3lhyV8ibArxTul0xFucF63lFv0MgDHVVWxWwm0B492aqLCbKrosZsYgl0C3AO1kFhClIbZ3I7iLhfco81HM+zuVwS2lNlCrhAWos6nsNS5Cgziwe5UzmotCRS1G8jUNC+p+vT2YaIcyQCOkk/XrzOmIWcd68YOc5xC/FwakS+8MSpliHovaCVQdGsvFfY7iiT1dLTTM9pbXr/sOpkkU4nmCslW7rWAhR40AUWVT+fVN374zY6A5ulAaFnTl3s95YbSEOwY+xC+Uz3eDQ2mA3PjbfmhX131g6DeUFvcQTU4NXUvTGt3H6o6L0QIsutePrwDha1P7ppQ8LZRn87GrJc7K0g==

install:
  - set PATH=C:\msys64\mingw64\bin;C:\msys64\mingw32\bin;C:\msys64\usr\bin;%PATH%;C:\Users\appveyor\.cargo\bin
  -
  - bash -lc "pacman --needed --noconfirm -Sy pacman-mirrors"
  - bash -lc "pacman --noconfirm -Syyu"
  - bash -lc "pacman --noconfirm -S mingw-w64-x86_64-toolchain bash"
  -
  - curl -SL https://win.rustup.rs/ -oC:\rustup-init.exe
  - C:\rustup-init.exe -y --default-host="x86_64-pc-windows-gnu"
  -
  - echo %GH_RSA_ENC% | base64 -d | gzip -d > gh_rsa

build: off
build_script:
  - git submodule update --init --recursive
  - cargo build --verbose --release
  - cargo doc --verbose --release
  -
  - echo "Update docs for commits %APPVEYOR_REPO_COMMIT%" >> "../DOC_UPDATE_MSG"
  - echo. >> "../DOC_UPDATE_MSG"
  - git log "%APPVEYOR_REPO_COMMIT%" -1 --pretty=oneline >> "../DOC_UPDATE_MSG"
  - cp gh_rsa %HOMEPATH%/.ssh/id_rsa
  - git clone -b doc "git@github.com:nabijaczleweli/wcxhead.rs.git" "../wcxhead.rs-doc"
  - cp -rf target/doc/* "../wcxhead.rs-doc"
  - pushd "../wcxhead.rs-doc"
  - git config --global user.email "nabijaczleweli@gmail.com"
  - git config --global user.name "Nabijaczleweli Autouploader Bot"
  - git config --global push.default simple
  - git add -- *
  - git commit -F "../DOC_UPDATE_MSG"
  - git push
  - popd
  -
  - cp -r target/doc "../wcxhead.rs-doc-v0.1.0"
  - pushd ..
  - tar -caf "wcxhead.rs-doc-v0.1.0.tbz2" "wcxhead.rs-doc-v0.1.0"
  - rm -rf "wcxhead.rs-doc-v0.1.0"
  - popd

test: off

artifacts:
  - path: wcxhead.rs-doc-v0.1.0.tbz2

deploy:
  provider: GitHub
  artifact: wcxhead.rs-doc-v0.1.0.tbz2
  auth_token:
    secure: q42bVqe6Vo/l9dQyArehIzuhIKUzH2JnsmPExSdliU0JdAn4cJIni87/JIh/QK+Z
  on:
    appveyor_repo_tag: true

notifications:
  - provider: Email
    to: nabijaczleweli@gmail.com
    on_build_status_changed: true
